const teamMembers = [
  {
    id: 1,
    name: "Shivani Arora",
    team: "technical",
    title: "Team Lead",
    instagram: "https://www.instagram.com/Shivani29.__/",
    linkedin: "https://www.linkedin.com/in/shivani-arora29",
    imgSrc: "https://i.ibb.co/w6Qjzp7/SHIVANI-ARORA.webp",
  },
  {
    id: 2,
    name: "Akshay Kumar Pandey",
    team: "technical",
    title: "Co-Lead",
    instagram: "https://www.instagram.com/kuchbhiakshay/",
    linkedin: "https://www.linkedin.com/in/akshay-kumar-pandey/",
    imgSrc: "https://i.ibb.co/1XkynJz/AKSHAY-KUMAR-PANDEY.jpg",
  },
  {
    id: 3,
    name: "Devarsh Shah",
    team: "technical",
    title: "Core Member",
    instagram: "https://www.instagram.com/devarshh_08/",
    linkedin:
      "https://www.linkedin.com/in/devarshshahh08/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/QXFZxJ1/DEVARSH-SHAH.jpg",
  },
  {
    id: 4,
    name: "Diksha Sinha",
    team: "technical",
    title: "Core Member",
    instagram: "https://www.instagram.com/dixpresss/",
    linkedin: "https://www.linkedin.com/in/diksha-sinha-46b786217/",
    imgSrc: "https://i.ibb.co/kXXt2XP/DIKSHA-SINHA.jpg",
  },
  {
    id: 5,
    name: "Mehul Singh",
    team: "technical",
    title: "Core Member",
    instagram: "https://www.instagram.com/_me._.si_/",
    linkedin:
      "https://www.linkedin.com/in/mehul-singh-73154b251?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/8XGhWPT/MEHUL-SINGH.jpg",
  },
  {
    id: 6,
    name: "Parth Dudani",
    team: "technical",
    title: "Core Member",
    instagram: "https://www.instagram.com/Parth_dudani/",
    linkedin:
      "https://www.linkedin.com/in/parth-dudani-97b594250?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/VNyLHd4/PARTH-DUDANI.jpg",
  },
  {
    id: 7,
    name: "Sawari Jamgaonkar",
    team: "technical",
    title: "Core Member",
    instagram: "https://www.instagram.com/Sawari_jamgaonkar/",
    linkedin: "www.linkedin.com/in/sawari-jamgaonkar-293399250",
    imgSrc: "https://i.ibb.co/nw4PgZD/SAWARI-JAMGAONKAR.jpg",
  },
  {
    id: 8,
    name: "Tanishk Jain",
    team: "technical",
    title: "Core Member",
    instagram: "https://www.instagram.com/tanishq0_0/",
    linkedin: "https://www.linkedin.com/in/tanishq-jain-823427226/",
    imgSrc: "https://i.ibb.co/XWrtDbX/TANISHQ-JAIN.jpg",
  },
  {
    id: 9,
    name: "Utkarsh Uttam",
    team: "technical",
    title: "Core Member",
    instagram: "https://www.instagram.com/utkarshuttam3/",
    linkedin: "https://www.linkedin.com/in/utkarsh-uttam-0884ab1b7/",
    imgSrc: "https://i.ibb.co/mGxt0n8/UTKARSH-UTTAM.jpg",
  },
  {
    id: 10,
    name: "Vinayak Pandey",
    team: "technical",
    title: "Core Member",
    instagram: "https://www.instagram.com/VintellX/",
    linkedin: "https://in.linkedin.com/in/vintellx",
    imgSrc: "https://i.ibb.co/0t8tC9F/VINAYAK-PANDEY.jpg",
  },
  {
    id: 11,
    name: "Arushi Saxena",
    team: "social-media",
    title: "Team Lead",
    instagram: "https://www.instagram.com/arrushhii/",
    linkedin: "https://www.linkedin.com/in/arushi-saxena-5104b0266/",
    imgSrc: "https://i.ibb.co/3yLWJbQ/ARUSHI-SAXENA.jpg",
  },
  {
    id: 12,
    name: "Suraj Raghuvanshi",
    team: "social-media",
    title: "Co-Lead",
    instagram: "https://www.instagram.com/surajraghuvanshiiii_/",
    linkedin: "https://www.linkedin.com/in/suraj-raghuvanshi-0b550821a/",
    imgSrc: "https://i.ibb.co/d5BBk6T/SURAJ-RAGHUVANSHI.jpg",
  },
  {
    id: 13,
    name: "Arnav Karn",
    team: "social-media",
    title: "Core Member",
    instagram: "https://www.instagram.com/arnav_065/",
    linkedin: "https://in.linkedin.com/in/arnavkarn",
    imgSrc: "https://i.ibb.co/6BvRJG0/ARNAV-KARN.jpg",
  },
  {
    id: 14,
    name: "Disha Gupta",
    team: "social-media",
    title: "Core Member",
    instagram: "https://www.instagram.com/dishaha.g/",
    linkedin:
      "https://www.linkedin.com/in/disha-gupta-430174245?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/Km0jyP3/DISHA-GUPTA.jpg",
  },
  {
    id: 15,
    name: "Kanishk Mathur",
    team: "pr-outreach",
    title: "Team Lead",
    instagram: "https://www.instagram.com/Wthkanishk/",
    linkedin: "https://www.linkedin.com/in/kanishk-mathur-9b54a0220/",
    imgSrc: "https://i.ibb.co/7k7RNJm/KANISHK-MATHUR.jpg",
  },
  {
    id: 16,
    name: "Eashan Batra",
    team: "pr-outreach",
    title: "Co-Lead",
    instagram: "https://www.instagram.com/eashaaaan/",
    linkedin:
      "https://www.linkedin.com/in/eashan-batra-bb6949221?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/dMWfN6N/EASHAN-BATRA.png",
  },
  {
    id: 17,
    name: "Ronith Dhanesh",
    team: "pr-outreach",
    title: "Core Member",
    instagram: "https://www.instagram.com/roniithh/",
    linkedin:
      "https://www.linkedin.com/me?trk=p_mwlite_feed_updates-secondary_nav",
    imgSrc: "https://i.ibb.co/863DwKz/RONITH-DHANESH.png",
  },
  {
    id: 18,
    name: "Supriya Mishra",
    team: "pr-outreach",
    title: "Core Member",
    instagram: "https://www.instagram.com/its_supriya_mishra/",
    linkedin: "https://www.linkedin.com/in/supriya-mishra-a32b4b251",
    imgSrc: "https://i.ibb.co/DrSgjvv/SUPRIYA-MISHRA.jpg",
  },
  {
    id: 19,
    name: "Vatsal Baranwal",
    team: "pr-outreach",
    title: "Core Member",
    instagram: "https://www.instagram.com/baranwal_vatsal/",
    linkedin:
      "https://www.linkedin.com/in/vatsal-baranwal-3607a1251/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/Y35jBrV/VATSAL-BARANWAL.jpg",
  },
  {
    id: 20,
    name: "Vikas Shukla",
    team: "pr-outreach",
    title: "Core Member",
    instagram: "https://www.instagram.com/01shuklavikas/",
    linkedin: "https://www.linkedin.com/in/vikas-shuklag/",
    imgSrc: "https://i.ibb.co/mR05LZH/VIKAS-SHUKLA.png",
  },

  {
    id: 21,
    name: "Dr. Subhash Patel",
    team: "other",
    title: "Faculty Coordinator",
    instagram: "#",
    linkedin:
      "https://www.linkedin.com/in/subhash-chandra-patel-638b2233?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/wQmXtCD/DR-SUBHASH-PATEL.jpg",
  },
  {
    id: 22,
    name: "Ayush Thakur",
    team: "other",
    title: "President",
    instagram: "https://www.instagram.com/ayuzhthakur/",
    linkedin:
      "https://www.linkedin.com/in/ayush-thakur-1b1127221/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/zXkMx9Z/AYUSH-THAKUR.jpg",
  },
  {
    id: 23,
    name: "Gourang Agarwal",
    team: "other",
    title: "Advisor",
    instagram: "https://www.instagram.com/gourangagrawal_/",
    linkedin: "https://www.linkedin.com/in/gourang-agrawal/",
    imgSrc: "#",
  },
  {
    id: 24,
    name: "Sanket Laxman Patil",
    team: "other",
    title: "Advisor",
    instagram: "https://instagram.com/sanket.patil____?igshid=NGVhN2U2NjQ0Yg==",
    linkedin: "https://www.linkedin.com/in/sanket-patil-483b12221/",
    imgSrc: "https://i.ibb.co/K0gcKKP/SANKET-LAXMAN-PATIL.jpg",
  },
  {
    id: 25,
    name: "Atul Joshy",
    team: "media",
    title: "Team Lead",
    instagram: "https://www.instagram.com/atuljoshy/",
    linkedin: "https://www.linkedin.com/in/atuljoshy/",
    imgSrc: "https://i.ibb.co/DfXTQnN/ATUL-JOSHY.jpg",
  },
  {
    id: 26,
    name: "Adhithya Raj P R",
    team: "media",
    title: "Co-Lead",
    instagram: "https://www.instagram.com/aaa.dhhi/",
    linkedin: "http://linkedin.com/in/adhithyapr03",
    imgSrc: "https://i.ibb.co/4JLz6jN/ADHITYA-RAJ.jpg",
  },
  {
    id: 27,
    name: "Amandeep Singh Khalsa",
    team: "media",
    title: "Core Member",
    instagram: "https://www.instagram.com/_amandeep.singh/",
    linkedin:
      "https://www.linkedin.com/in/amandeep-singh-khalsa-61173a250?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/MBCqs5p/AMANDEEP-SINGH.jpg",
  },
  {
    id: 28,
    name: "Kumarvaishnav",
    team: "media",
    title: "Core Member",
    instagram: "https://www.instagram.com/lmaokv._/",
    linkedin: "https://in.linkedin.com/in/kumarvaishnav-dwivedi-926478216",
    imgSrc: "https://i.ibb.co/wBrP2X2/KUMARVAISHNAV.jpg",
  },
  {
    id: 29,
    name: "Sidharth Sonu Kumar",
    team: "media",
    title: "Core Member",
    instagram:
      "https://instagram.com/sidhyyuu?utm_source=qr&igshid=MzNlNGNkZWQ4Mg==",
    linkedin: "https://www.linkedin.com/in/sidharth-kumar-18b905282",
    imgSrc: "https://i.ibb.co/vmHVc8Z/SIDHARTH-SONU-KUMAR.jpg",
  },
  {
    id: 30,
    name: "Shantanu Modhave",
    team: "event",
    title: "Team Lead",
    instagram: "https://www.instagram.com/shantanu.modhave/",
    linkedin:
      "https://www.linkedin.com/in/shantanu-modhave-?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/kQgc2Jh/SHANTANU-MODHAVE-CHANDRKANT.webp",
  },
  {
    id: 31,
    name: "Ashmit Pandey",
    team: "event",
    title: "Co-Lead",
    instagram: "https://www.instagram.com/ashmit.pandey.03/",
    linkedin: "https://www.linkedin.com/in/ashmit-pandey-438760228",
    imgSrc: "https://i.ibb.co/KwRY8Vy/ASHMIT-PANDEY.jpg",
  },
  {
    id: 32,
    name: "Abhishek Bhavsar",
    team: "event",
    title: "Core Member",
    instagram: "https://www.instagram.com/kuchbhiabhi_/",
    linkedin: "https://www.linkedin.com/in/abhishek-bhavsar-529b75222",
    imgSrc: "https://i.ibb.co/L9nv0yp/ABHISHEK-BHAVSAR.jpg",
  },
  {
    id: 33,
    name: "Gayatri Mistary",
    team: "event",
    title: "Core Member",
    instagram: "https://www.instagram.com/gayatrigawle_/",
    linkedin:
      "https://www.linkedin.com/in/gayatri-mistary-b53693224?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    imgSrc: "https://i.ibb.co/NxLWh2j/GAYATRI-MISTARY-BHATU.jpg",
  },
  {
    id: 34,
    name: "Pranav Sanjay Jahagirdar",
    team: "event",
    title: "Core Member",
    instagram: "https://www.instagram.com/pranavjahagirdar_/",
    linkedin:
      "https://www.linkedin.com/in/pranav-sanjay-jahagirdar-531635251?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    imgSrc: "https://i.ibb.co/Dtvt2Lw/PRANAV-SANJAY-JAHAGIRDAR.jpg",
  },
  {
    id: 35,
    name: "Tushita Gakkhar",
    team: "event",
    title: "Core Member",
    instagram: "https://www.instagram.com/tushita_gakkhar/",
    linkedin:
      "https://www.linkedin.com/in/tushita-gakkhar-080942251?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/jwM3N6h/TUSHITA-GAKKHAR.jpg",
  },
  {
    id: 36,
    name: "Vivek Kaushik",
    team: "event",
    title: "Core Member",
    instagram: "https://www.instagram/kaushik.vivek/",
    linkedin:
      "https://www.linkedin.com/in/vivek-kaushik-766723250?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/KxYH3PG/VIVEK-KAUSHIK.jpg",
  },
  {
    id: 37,
    name: "Aarushi Verma",
    team: "design",
    title: "Team Lead",
    instagram: "https://www.instagram.com/ayerushii/",
    linkedin: "https://www.linkedin.com/in/aarushi-verma-a72ba4226/",
    imgSrc: "https://i.ibb.co/ZxNGYj8/AARUSHI-VERMA.jpg",
  },
  {
    id: 38,
    name: "Ayushka Behere",
    team: "design",
    title: "Co-Lead",
    instagram: "https://www.instagram.com/ayushka_b/",
    linkedin:
      "https://www.linkedin.com/in/ayushka-behere-209946227?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/WcGsm3P/AYUSHKA-RAVI-BEHERE.jpg",
  },
  {
    id: 39,
    name: "Harshit Gujar",
    team: "design",
    title: "Core Member",
    instagram: "https://www.instagram.com/harshitgujar__16/",
    linkedin:
      "https://www.linkedin.com/in/harshit-gujar-8b8627297?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/xDBVZT2/HARSHIT-GUJAR.jpg",
  },
  {
    id: 40,
    name: "Maher Sarah Jafri",
    team: "design",
    title: "Core Member",
    instagram: "https://www.instagram.com/maher.sarahh/",
    linkedin:
      "https://www.linkedin.com/in/mahersarahjafri?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    imgSrc: "https://i.ibb.co/FmynWzW/MAHER-SARAH-JAFRI.jpg",
  },
  {
    id: 41,
    name: "Riya Verma",
    team: "design",
    title: "Core Member",
    instagram: "https://www.instagram.com/beeriyal/",
    linkedin: "https://www.linkedin.com/in/riya-verma-41558724",
    team: "design",
    title: "Core Member",
    instagram: "https://www.instagram.com/beeriyal/",
    linkedin:
      "https://www.linkedin.com/in/riya-verma-41558724b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/wdKN8hn/RIYA.jpg",
  },
  {
    id: 42,
    name: "Shreeja Pandey",
    team: "content",
    title: "Team Lead",
    instagram: "https://www.instagram.com/Shreexxaa/",
    linkedin: "https://www.linkedin.com/in/shreeja-pandey-6b0874252/",
    imgSrc: "https://i.ibb.co/cT1z8BQ/SHREEJA-PANDEY.jpg",
  },
  {
    id: 43,
    name: "Vaibhavi Mudgal",
    team: "content",
    title: "Co-Lead",
    instagram: "https://instagram.com/mudgalvaibhavi?igshid=NGVhN2U2NjQ0Yg==",
    linkedin:
      "https://www.linkedin.com/in/vaibhavimudgal15?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    imgSrc: "https://i.ibb.co/jRzHyLQ/VAIBHAVI-MUDGAL.jpg",
  },
  {
    id: 44,
    name: "Mehar Parnami",
    team: "content",
    title: "Core Member",
    instagram: "https://www.instagram.com/Mehar_631/",
    linkedin: "https://www.linkedin.com/feed/",
    imgSrc: "https://i.ibb.co/5Khs4Yh/MEHER-PARNAMI.jpg",
  },
  {
    id: 45,
    name: "R Simran Nair",
    team: "content",
    title: "Core Member",
    instagram: "https://www.instagram.com/smriti.__./",
    linkedin: "https://www.linkedin.com/in/simran-nair-b8b85a257/",
    imgSrc: "https://i.ibb.co/JkxMnKM/R-SIMRAN-NAIR.jpg",
  },
];

export default teamMembers;
